### ISSUE TITLE
For bulk RNAseq

### ISSUE THREAD

**Issue by hchetia** [SONGDONGYUAN1994/PseudotimeDE#4]
Has this method been tested also for bulk-RNAseq data?

**Comment by SONGDONGYUAN1994** [comment]
Hi,
This method hasn't been tested for bulk-RNAseq data. Based on my knowledge, people do not use pseudotime in bulk-RNA-seq (if I am wrong, please tell me!) Of course, you can try the "fix" mode if your data is time-course data. However, please notice that a GAM needs many time points due to its high model degree of freedom (perhaps more than 10 time points). If you only have a few time points the method will not work. Thanks!

**Comment by hchetia** [comment]
Hi @SONGDONGYUAN1994 
Thanks for the reply.
Literature shows that Phenopath by Kieran Campbell is one of the tools that can allow pseudotime based inference from bulk RNAseq data.
